add_newline = false

# MAIN FORMAT
# Note the double backslashes \\( and \\)
format = """
[┌──\\(](bold blue)$username[@](bold white)$hostname[\\)-](bold blue)$directory$git_branch
$character"""

# USERNAME
[username]
style_user = "green bold"
style_root = "red bold"
# For dynamic name use [user] instead of static name
# $user for dynamic name
format = "[project-lbr]($style)"
show_always = true

# HOSTNAME
[hostname]
style = "bold white"
ssh_only = false
format = "[$hostname]($style)"

# DIRECTORY
[directory]
style = "cyan bold"
read_only = " 🔒"
truncation_length = 3
# Here too we must double the backslashes: \\[ and \\]
format = "[ \\[ ](bold blue)[$path]($style)[ \\] ](bold blue)"

# SECOND LINE
[character]
success_symbol = "[└─❯](bold green)"
error_symbol = "[└─❯](bold red)"
